CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 VARCHAR(120)             NOT NULL,
    password_hash         VARCHAR(100)             NOT NULL,
    full_name             VARCHAR(100)             NOT NULL,
    role                  VARCHAR(20)              NOT NULL,
    failed_login_attempts INTEGER                  NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP WITH TIME ZONE,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    version               BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE TABLE accounts (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number         VARCHAR(12)              NOT NULL,
    owner_id               BIGINT                   NOT NULL,
    nickname               VARCHAR(40),
    type                   VARCHAR(20)              NOT NULL,
    currency               VARCHAR(3)               NOT NULL,
    balance                NUMERIC(19, 2)           NOT NULL,
    status                 VARCHAR(20)              NOT NULL,
    interest_rate          NUMERIC(5, 2)            NOT NULL,
    daily_withdrawal_limit NUMERIC(19, 2)           NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at              TIMESTAMP WITH TIME ZONE,
    version                BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT uk_accounts_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT ck_accounts_type CHECK (type IN ('CHECKING', 'SAVINGS')),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_accounts_owner ON accounts (owner_id);

CREATE TABLE transactions (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                  BIGINT                   NOT NULL,
    reference                   VARCHAR(20)              NOT NULL,
    type                        VARCHAR(20)              NOT NULL,
    amount                      NUMERIC(19, 2)           NOT NULL,
    balance_after               NUMERIC(19, 2)           NOT NULL,
    description                 VARCHAR(140),
    counterparty_account_number VARCHAR(12),
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_transactions_account_created ON transactions (account_id, created_at);
CREATE INDEX idx_transactions_reference ON transactions (reference);

CREATE TABLE idempotency_keys (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key    VARCHAR(100)             NOT NULL,
    user_id            BIGINT                   NOT NULL,
    request_hash       VARCHAR(64)              NOT NULL,
    transfer_reference VARCHAR(20)              NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_idempotency_user_key UNIQUE (user_id, idempotency_key),
    CONSTRAINT fk_idempotency_user FOREIGN KEY (user_id) REFERENCES users (id)
);
